# Build args
ARG UV_VERSION=latest
ARG CUDA_VERSION=13.2.1
ARG UBUNTU_VERSION=24.04
#ARG UBUNTU_VERSION=22.04


### STAGE 1: BUILDER

# uv installer layer
FROM ghcr.io/astral-sh/uv:$UV_VERSION AS uv

# Base CUDA image
#FROM nvidia/cuda:$CUDA_VERSION-runtime-ubuntu$UBUNTU_VERSION
FROM nvidia/cuda:${CUDA_VERSION}-cudnn-runtime-ubuntu${UBUNTU_VERSION} AS builder

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3.12 \
    python3.12-dev \
    python3-pip \
    build-essential \
    git \
    ninja-build \
    pkg-config \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=uv --chown=vscode: /uv /uvx /bin/

ENV UV_PYTHON=python3.12 \
    UV_LINK_MODE=copy \
    UV_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cu132"

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./

RUN uv sync --frozen --no-install-project --no-dev

COPY src/ src/
COPY tools/ tools/

RUN uv sync --frozen --no-dev


### STAGE 2: RUNTIME

FROM nvidia/cuda:${CUDA_VERSION}-cudnn-runtime-ubuntu${UBUNTU_VERSION}

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_LINK_MODE=copy

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.12 \
    python3.12-venv \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

#COPY --from=builder /root/.local /root/.local
COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app/src /app/src
COPY --from=builder /app/tools /app/tools

#ENV PATH="/root/.local/bin:$PATH"
ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "-m", "kldm_new.scripts.train", "experiment=debug"]
